collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.5177239
color:
  saturation: 0.7186177130788565
  brandStrength: 0.1932104879524559
  lightness: 0.7783576701767743
  brandColors:
    - '#FFFFFF'
    - '#191C21'
    - '#868477'
    - '#B5B6B1'
    - '#265523'
  rhythmicContrast: 0.8005897449329495
layout_spectrum: 0.9029851
name: Defence Dogs
